name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Kodları Çek
        uses: actions/checkout@v4

      - name: AutoHotkey v2 ve Derleyiciyi Kur
        shell: pwsh
        run: |
          # AHK v2.0.20 indir ve zipten çıkar
          Invoke-WebRequest -Uri "https://www.autohotkey.com/download/ahk-v2.zip" -OutFile "ahk.zip"
          Expand-Archive -Path "ahk.zip" -DestinationPath "ahk_dir"
          
          # Derleyiciyi (Ahk2Exe) indir
          Invoke-WebRequest -Uri "https://www.autohotkey.com/download/ahk2exe.zip" -OutFile "compiler.zip"
          Expand-Archive -Path "compiler.zip" -DestinationPath "compiler_dir"

      - name: 64-bit Derle (x64)
        shell: pwsh
        run: |
          .\compiler_dir\Ahk2Exe.exe /in "src/AS Icon Viewer.ahk" /out "AS-Icon-Viewer-x64.exe" /icon "src/app_icon.ico" /base "ahk_dir/v2/AutoHotkey64.exe" /compress 1

      - name: 32-bit Derle (x32)
        shell: pwsh
        run: |
          .\compiler_dir\Ahk2Exe.exe /in "src/AS Icon Viewer.ahk" /out "AS-Icon-Viewer-x32.exe" /icon "src/app_icon.ico" /base "ahk_dir/v2/AutoHotkey32.exe" /compress 1

      - name: Release Oluştur ve Yükle
        uses: softprops/action-gh-release@v2
        with:
          files: |
            AS-Icon-Viewer-x64.exe
            AS-Icon-Viewer-x32.exe
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
