name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Örn: v1.0.1 etiketiyle push yapıldığında çalışır

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Kodları Çek (Checkout)
        uses: actions/checkout@v4 # Kararlılık için v4 önerilir ama v6.0.2 de yazabilirsiniz

      - name: 64-bit Derle (v2)
        uses: Nekosina/github-action-ahk2exe@v1.2.3
        with:
          ahk-version: 'v2.0.20'
          in: 'src/AS Icon Viewer.ahk'
          out: 'AS-Icon-Viewer-x64.exe'
          icon: 'src/app_icon.ico'
          base: 'AutoHotkey64.exe'
          compress: 'true'

      - name: 32-bit Derle (v2)
        uses: Nekosina/github-action-ahk2exe@v1.2.3
        with:
          ahk-version: 'v2.0.20'
          in: 'src/AS Icon Viewer.ahk'
          out: 'AS-Icon-Viewer-x32.exe'
          icon: 'src/app_icon.ico'
          base: 'AutoHotkey32.exe'
          compress: 'true'

      - name: Release Oluştur ve Yükle
        uses: softprops/action-gh-release@v2 # Bu da güncellendi
        with:
          files: |
            AS-Icon-Viewer-x64.exe
            AS-Icon-Viewer-x32.exe
          generate_release_notes: true # Otomatik değişim günlüğü oluşturur
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
